package com.phase1.api;
import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import com.phase1.models.User;
import com.phase1.services.IUserServices;
import java.util.List;

@RestController
public class UserAPIController {

	@Autowired //This means to get the bean called userRepository Which is auto-generated by Spring, we will use it to handle the data
    private IUserServices service;

	@RequestMapping(value="/add", method=RequestMethod.POST)
	    public boolean add(@RequestBody User user)
	    {
	        // @RequestParam means it is a parameter from the GET or POST request
	        return service.addUser(user);
	    }

	@RequestMapping(value="/getAll", method=RequestMethod.GET)
	    public List<User> getAllUsers()
	 {
	        // This returns a JSON or XML with the users
	        return service.getAllUsers();
	 }

}
